# delete a listing by id
@api = http://localhost:5019
@listingId = 679b2d3a99092dd6476c4a4a

DELETE  {{api}}/listings/{{listingId}}
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzliMjViNTNmMzZhNDdhZTdlMDg2MmEiLCJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwibmJmIjoxNzM4MjI4MzIxLCJleHAiOjE3MzgyMzE5MjEsImlhdCI6MTczODIyODMyMSwiaXNzIjoiSG91c2VSZW50YWxTeXN0ZW0iLCJhdWQiOiJIb3VzZVJlbnRhbEF1ZGllbmNlIn0.13nZ8aEz392ibOFDddH9meuPVtUhI1pLYWs6nBBCj0o