@api = http://localhost:5019

POST {{api}}/auth/register
Content-Type:  application/json

{
  "Email": "johndoe@gmail.com",
  "Password": "password",
  "FullName": "John Doe",
  "Phone": "012344567",
  "Address": "A.a"
}